names = ["Qualcomm",
"Hewlett Packard Enterprise",
"British American Tobacco",
"Visa",
"China Pacific Insurance",
"MetLife",
"AstraZeneca",
"Altria Group",
"SAP",
"Costco Wholesale",
"Travelers",
"Philip Morris International",
"Union Pacific",
"Delta Air Lines",
"Southern Company",
"Lowe's",
"National Grid",
"Legal & General Group",
"McKesson",
"Christian Dior",
"PTT PCL",
"Dai-ichi Life Insurance",
"Twenty-First Century Fox",
"Canadian Imperial Bank",
"FedEx",
"GlaxoSmithKline",
"Deutsche Post",
"3M",
"L'Oréal Group",
"Aflac",
"Allstate",
"Hitachi",
"Brookfield Asset Management",
"BT Group",
"NextEra Energy",
"BlackRock",
"Continental",
"MS&AD Insurance",
"Aviva",
"Cigna",
"Phillips 66",
"Valero Energy",
"Enbridge",
"Mondelēz International",
"People's Insurance Company",
"McDonald's",
"ArcelorMittal",
"East Japan Railway",
"Itochu",
"Japan Tobacco",
"EI du Pont de Nemours",
"Eli Lilly",
"Panasonic",
"Sun Hung Kai Properties",
"Fiat Chrysler Automobiles",
"LafargeHolcim",
"Qatar National Bank",
"Target",
"Fresenius",
"Danaher",
"Danske Bank",
"General Dynamics",
"Reynolds American",
"Denso",
"Bristol-Myers Squibb",
"CRRC",
"ABB",
"Exelon",
"Cathay Financial",
"Sun Life Financial",
"Repsol",
"Kroger",
"Abbott Laboratories",
"HCA Holdings",
"State Bank of India",
"DBS Group",
"Oil & Natural Gas",
"American Airlines Group",
"BB&T",
"Nike",
"Schneider Electric",
"Thermo Fisher Scientific",
"Danone",
"Samsung Life Insurance",
"Air Liquide",
"Huaxia Bank",
"Orix",
"Bank of Beijing",
"HDFC Bank",
"KBC Group",
"Deere & Company",
"Diageo",
"Central Japan Railway",
"Liberty Global",
"Indian Oil",
"Shinhan Financial Group",
"Canon",
"Synchrony Financial",
"Saint-Gobain",
"United Continental Holdings",
"Carnival",
"HP",
"Accenture",
"Country Garden Holdings",
"State Street",
"Volvo Group",
"Inditex",
"Seven & I Holdings",
"Mitsubishi Electric",
"Bridgestone",
"PG&E",
"Cardinal Health",
"Telstra",
"Dominion Resources",
"Nomura",
"Raytheon",
"Henkel",
"Marathon Petroleum",
"Merck",
"Peugeot",
"Tata Motors",
"Archer Daniels Midland",
"CNP Assurances",
"Natixis",
"China Huarong Asset Management",
"Imperial Tobacco Group",
"BCE",
"Northrop Grumman",
"LyondellBasell Industries",
"Posco",
"Telecom Italia",
"Oversea-Chinese Banking",
"KB Financial Group",
"Charles Schwab",
"Orange",
"Surgutneftegas",
"Sompo",
"Gas Natural Fenosa",
"WPP",
"Bank Of Shanghai",
"ICICI Bank",
"Poly Real Estate",
"Hyundai Mobis",
"DNB",
"Philips",
"AmerisourceBergen",
"Heineken Holding",
"CRH",
"Discover Financial Services",
"Safran",
"Etisalat",
"CaixaBank",
"Eaton",
"Fubon Financial",
"Sumitomo",
"SunTrust Banks",
"Greenland Holdings Group",
"China Cinda Asset Management",
"Anglo American",
"China Resources Land",
"Royal Ahold Delhaize N.V.",
"SingTel",
"United Overseas Bank",
"Subaru",
"Automatic Data Processing",
"Midea Group",
"Linde",
"KIA Motors",
"Hartford Financial Services",
"Southwest Airlines",
"América Móvil",
"Principal Financial Group",
"Fannie Mae",
"Ameriprise Financial",
"Macquarie Group",
"Carrefour",
"Celgene",
"China Evergrande Group",
"Takeda Pharmaceutical",
"SK Hynix",
"Saudi Telecom",
"Tyson Foods",
"Sinohydro Group",
"Reckitt Benckiser Group",
"CSX",
"Freddie Mac",
"Lincoln National",
"Kinder Morgan",
"Power Corp of Canada",
"BP",
"Chevron",
"Michelin Group",
"Cheung Kong Property Holdings",
"SK Holdings",
"Gree Electric Appliances",
"BAE Systems",
"Bank Of Jiangsu",
"Edison International",
"Kansai Electric Power",
"New China Life Insurance",
"Starbucks",
"Centrica",
"Biogen",
"Canadian National Railway",
"HDFC",
"Novo Nordisk",
"Swedbank",
"Tata Consultancy Services",
"Monsanto",
"Mastercard",
"Femsa",
"PayPal",
"Progressive",
"Svenska Handelsbanken",
"Mitsui Fudosan",
"SEB",
"Bank Rakyat Indonesia",
"Texas Instruments",
"Wilmar International",
"Daiwa House Industry",
"Baidu",
"Consolidated Edison",
"Maybank",
"DISH Network",
"Citic Securities",
"American Electric",
"Suzuki Motor",
"VTB Bank",
"Metallurgical Corp of China",
"Petrobras",
"Norfolk Southern",
"TJX Cos",
"Investor AB",
"American International Group",
"Sempra Energy",
"International Airlines",
"SSE",
"eBay",
"NTPC",
"Old Mutual",
"Magna International",
"China Yangtze Power",
"NN Group",
"Sumitomo Mitsui Trust",
"General Mills",
"Talanx",
"The Priceline Group",
"EXOR",
"Glencore International",
"Vodafone",
"Huaneng Power International",
"Standard Bank Group",
"Swiss Life Holding",
"FirstRand",
"Sysco",
"International Paper",
"Vivendi",
"Kimberly-Clark",
"National Commercial Bank",
"Erste Group Bank",
"Baoshan Iron & Steel",
"Eni",
"Saudi Electricity",
"Corning",
"Daikin Industries",
"Mitsubishi Chemical",
"Becton Dickinson",
"SK Innovation",
"Humana",
"Emerson Electric",
"Nippon Steel & Sumitomo Metal",
"Deutsche Bank",
"Toyota Industries",
"Pernod Ricard",
"Aon",
"IntercontinentalExchange",
"Stryker",
"Fujifilm Holdings",
"Fosun International",
"Sony",
"Chubu Electric Power",
"Las Vegas Sands",
"Xcel Energy",
"Fifth Third Bancorp",
"Bouygues",
"ENGIE",
"Steinhoff International",
"Wheelock",
"Marsh & McLennan",
"CBS",
"Fujitsu",
"Statoil",
"Wesfarmers",
"Axis Bank",
"HeidelbergCement",
"Illinois Tool Works",
"Formosa Petrochemical",
"Marriott International",
"Adidas",
"CLP Holdings",
"Thomson Reuters",
"Kering",
"Colgate-Palmolive",
"Richemont",
"Shin-Etsu Chemical",
"Mapfre",
"Poste Italiane",
"Aisin Seiki",
"Mitsubishi",
"Mitsubishi Estate",
"PPL",
"Waste Management",
"Micron Technology",
"Larsen & Toubro",
"Aegon",
"Teva Pharmaceutical",
"Compass Group",
"Suncor Energy",
"EDP-Energias de Portugal",
"Syngenta",
"Tenaga Nasional",
"Credit Suisse Group"
]